# yaml-language-server: $schema=../config.schema.json
schemaVersion: 2
packVersion: "1.0.0"
profile:
  name: Example Modpack
  icon: Furnace
  version: neoforge-21.1.216
  jvmArgs: -Xms4G -Xmx8G
modLoader:
  name: NeoForge
  url: https://maven.neoforged.net/releases/net/neoforged/neoforge/21.1.216/neoforge-21.1.216-installer.jar
  hash: 62118f0aed41e5a5c2b1b9e4feb35a22c4609548
  autoOpen: true
mods:
  - name: Create
    type: curseforge
    projectId: 328085
    fileId: 7178775
    hash: "eee603ac7b083c9cd3a8ded4d4e3ed1a9a836f96"
    side: both
  - name: Curios API (Forge/NeoForge)
    type: curseforge
    projectId: 309927
    fileId: 6529130
    hash: "418fcd42e3a7844c9bdc71c9b6401fdb3894e0c4"
    side: both
  - name: EMI
    type: curseforge
    projectId: 580555
    fileId: 6420931
    hash: "cbbd038194cd63249db185c53b1d50a1767f80a3"
    side: both
  - name: Iris Shaders
    type: curseforge
    projectId: 455508
    fileId: 6661598
    hash: "a3e6355915c7d3b2bc392724795113e51d289378"
    side: client
  - name: Simple Backups
    type: curseforge
    projectId: 583228
    fileId: 7151913
    hash: "35bb3b98f330e0f6d08466860157a578a1ecfca2"
    side: server
  - name: Sodium
    type: curseforge
    projectId: 394468
    fileId: 6382651
    hash: "38af70fa4dc4b2aaac636e92fdba3bedd5a025e1"
    side: client
resources:
  - name: BSL Shaders
    type: curseforge
    projectId: 322506
    fileId: 6514910
    hash: "82eb9981a31a4753bb5022b5f64d5ec4f6a27071"
    targetDir: shaderpacks
    side: client
